"""
Task 1: THEORETICAL analysis of π_R(x)

Using the key structural observation:
  R(p) = (p²-1)/(2p) ~ p/2

The set of achievable R values is a multiplicative free semigroup
generated by {R(p^a): p prime, a ≥ 1}.

This is analogous to counting "R-integers" ≤ x in a log-scale.
"""

import math
from fractions import Fraction

def sieve_primes(limit):
    is_prime = bytearray([1]) * (limit + 1)
    is_prime[0] = is_prime[1] = 0
    for i in range(2, int(limit**0.5) + 1):
        if is_prime[i]:
            is_prime[i*i::i] = bytearray(len(is_prime[i*i::i]))
    return [i for i in range(2, limit+1) if is_prime[i]]

def exact_pi_R(x_max, primes):
    """Exact count using DFS with Fraction arithmetic."""
    x_frac = Fraction(x_max)

    # Prime R-values ≤ x
    prime_r = []
    for p in primes:
        rp = Fraction(p*p - 1, 2*p)
        if rp > x_frac:
            break
        prime_r.append(rp)

    # All prime-power R-values ≤ x (grouped by prime)
    all_generators = []  # list of lists: generators[i] = list of choices for prime primes[i]
    for i, p in enumerate(primes):
        choices = []
        for a in range(1, 50):
            rpa = Fraction(p**(a+1) - 1, p * (a+1))
            if rpa > x_frac:
                break
            choices.append(rpa)
        if choices:
            all_generators.append(choices)
        # Stop when smallest choice for this prime exceeds x
        if Fraction(p*p - 1, 2*p) > x_frac:
            break

    n_gen = len(all_generators)
    distinct = set()
    distinct.add(Fraction(1))

    def dfs(idx, current):
        for i in range(idx, n_gen):
            for choice in all_generators[i]:
                new = current * choice
                if new > x_frac:
                    break  # choices within generator i are increasing
                if new not in distinct:
                    distinct.add(new)
                    dfs(i + 1, new)

    dfs(0, Fraction(1))
    return len(distinct)

def main():
    print("="*70)
    print("TASK 1: THEORETICAL ANALYSIS")
    print("="*70)

    primes = sieve_primes(300000)

    # Compute for moderate x values
    x_vals = [10, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000]

    print("\nExact π_R(x) computation:")
    print(f"{'x':>8} {'π_R(x)':>10} {'π(2x)':>8} {'comp':>8} {'π_R/π(2x)':>12} {'ln(ratio)':>10}")
    print("-"*58)

    data = []
    for x in x_vals:
        pi_x = exact_pi_R(x, primes)
        pi_2x = sum(1 for p in primes if p <= 2*x)
        ratio = pi_x / pi_2x if pi_2x > 0 else 0
        ln_ratio = math.log(ratio) if ratio > 0 else 0
        comp = pi_x - pi_2x
        data.append((x, pi_x, pi_2x, comp))
        print(f"{x:>8} {pi_x:>10} {pi_2x:>8} {comp:>8} {ratio:>12.4f} {ln_ratio:>10.4f}")

    print("\nAsymptotic form testing:")
    print(f"{'x':>8} {'π_R(x)':>10} {'2x/lnx':>10} {'ratio1':>8} {'x·(lnx)^0.5':>13} {'ratio2':>8}")
    print("-"*60)
    for x, pi_x, pi_2x, comp in data:
        if x > 1:
            lnx = math.log(x)
            f1 = 2*x / lnx
            f2 = x * math.sqrt(lnx)
            r1 = pi_x / f1
            r2 = pi_x / f2
            print(f"{x:>8} {pi_x:>10} {f1:>10.2f} {r1:>8.4f} {f2:>13.2f} {r2:>8.4f}")

    # K-prime breakdown for x=10000
    print("\n" + "="*70)
    print("K-PRIME PRODUCT BREAKDOWN for x=10000")
    print("="*70)

    x_test = 10000
    x_frac = Fraction(x_test)
    prime_list = [p for p in primes if Fraction(p*p-1, 2*p) <= x_frac]
    prime_r_vals = [Fraction(p*p-1, 2*p) for p in prime_list]

    # Count distinct products by number of prime factors
    by_k = [set() for _ in range(12)]
    by_k[0].add(Fraction(1))

    def dfs_k(idx, current, k):
        if k < len(by_k):
            by_k[k].add(current)
        for i in range(idx, len(prime_r_vals)):
            new = current * prime_r_vals[i]
            if new > x_frac:
                break
            if k + 1 < len(by_k):
                dfs_k(i + 1, new, k + 1)

    dfs_k(0, Fraction(1), 0)

    total = 0
    for k in range(len(by_k)):
        # New distinct values at this k (not seen at smaller k)
        new_at_k = by_k[k]
        for j in range(k):
            new_at_k = new_at_k - by_k[j]
        n = len(by_k[k])
        n_new = len(new_at_k)
        if n > 0:
            print(f"  k={k}: {n:>8} products (not all distinct from lower k), {n_new:>8} truly new")
        total += n_new

    print(f"  Total: {total}")

    print("\n" + "="*70)
    print("THEORETICAL BOUNDS AND CONCLUSION")
    print("="*70)

    print("""
EXACT LOWER BOUND (from primes):
  The values R(p) = (p²-1)/(2p) are distinct for all primes p
  (they are strictly increasing: dR/dp = (p²+1)/(2p²) > 0).
  Count: π(2x+1) ~ 2x/ln(2x) ~ 2x/ln(x).

COMPOSITE CONTRIBUTION:
  From k-prime products R(p₁)R(p₂)...R(pₖ) ≤ x where p₁<p₂<...<pₖ:
  Number of products ~ (1/k!) · [π(2x^{1/k})]^k for the "equal split" case.
  More precisely: these products have the structure of squarefree numbers
  in the "R-world" with generators R(p) ≈ p/2.

  Total composite contribution from k=2:
    C₂(x) = # {R(p)R(q): p<q, R(p)R(q)≤x}
           ≈ ∑_{p prime, R(p) ≤ x^{1/2}} π(2x/R(p))
           ≈ ∑_{p ≤ 2√x} (2x/R(p)) / ln(2x/R(p))
           ≈ (2x/ln x) ∑_{p ≤ 2√x} 1/R(p)
           = (2x/ln x) ∑_{p ≤ 2√x} 2p/(p²-1)
           ~ (2x/ln x) · 2 ∑_{p ≤ 2√x} 1/p
           ~ (2x/ln x) · 2 · (1/2)ln ln(2√x)  [Mertens]
           ~ (2x/ln x) · ln ln x

TOTAL:
  π_R(x) ~ (2x/ln x) · (1 + ln ln x + higher order)

This means π_R(x) is NOT exactly x/ln(x) or x√(ln x),
but grows as:

  π_R(x) ~ (2x/ln x) · (ln ln x)^α   for some α

or possibly:

  π_R(x) ~ C · x / (ln x)^β   for some β < 1

The Selberg-Sathe formula for the count of n with ω(n)=k gives:
  #{n ≤ x: ω(n) = k} ~ (x/ln x) · (ln ln x)^{k-1} / (k-1)!

Summing over k: ∑_{k≥1} (x/ln x) · (ln ln x)^{k-1} / (k-1)!
                = (x/ln x) · ∑_{j≥0} (ln ln x)^j / j!
                = (x/ln x) · e^{ln ln x}
                = (x/ln x) · ln x
                = x

...which is just x (as expected: all n ≤ x).

For R-values the situation is different: we're counting DISTINCT products,
and there are COLLISIONS (R(p₁)R(p₂) = R(q₁)R(q₂) can happen).

The numerical data shows ratio π_R(x)/π(2x) grows roughly as:
""")

    print("  Ratio π_R(x)/π(2x) at computed points:")
    for x, pi_x, pi_2x, comp in data:
        if pi_2x > 0:
            ratio = pi_x / pi_2x
            lnlnx = math.log(math.log(x)) if x > 1 else 0
            print(f"    x={x:>6}: ratio={ratio:.4f}, ln(ln(x))={lnlnx:.4f}, ratio/ln(ln(x))={ratio/lnlnx:.4f}")

    print("""
CONCLUSION:
  The ratio π_R(x)/π(2x) grows roughly as ln(ln(x)),
  suggesting:

    π_R(x) ~ 2x/ln(x) · ln(ln(x))

  This is consistent with the Selberg-Sathe heuristic.

  The empirical "~4.3·x·√(ln x)" was a LOCAL fit for moderate x
  that coincidentally matched the data, but has the wrong asymptotic form.

  The CORRECT asymptotic appears to be:

    π_R(x) ~ C · x · ln(ln x) / ln(x)

  where C ≈ 2 (from the prime bijection R(p) ↔ p/2).
""")

if __name__ == "__main__":
    main()
