"""n6-architecture Constants Registry — 494 constants for Math Atlas scanning."""

# Auto-generated from n6-architecture project
# Core theorem: sigma(6)*phi(6) = 6*tau(6) = 24

N6_CONSTANTS = {
    "THM-1": {"value": "σ(n)·φ(n) = n·τ(n) ⟺ n = 6 (n ≥ 2)", "application": "R_local case analysis", "domain": "**PROVED**"},
    "THM-2": {"value": "Among perfect numbers, φ/τ = 1/2 only at n=6", "application": "Euler form analysis", "domain": "**PROVED**"},
    "THM-3": {"value": "For semiprimes pq: (p²-1)(q²-1) = 4pq ⟺ (p,q)=(2,3)", "application": "Quadratic formula", "domain": "**PROVED**"},
    "τ²/σ": {"value": "4/3 ≈ 1.333", "application": "FFN expansion ratio", "domain": "AI"},
    "σ±μ": {"value": "{11,13} twin primes", "application": "TCP+DNS=24=core theorem", "domain": "BT-13 ⭐⭐⭐"},
    "σ(σ-μ)+sopfr+μ/P₂": {"value": "137.03571", "application": "1/α (fine structure, 2.08 ppm)", "domain": "Particle, BT-20"},
    "sopfr/((σ-sopfr)·n)": {"value": "5/42=0.1190", "application": "α_s(M_Z) (0.97%)", "domain": "Particle, BT-20"},
    "(n/φ)/(σ+μ)": {"value": "3/13=0.2308", "application": "sin²θ_W(M_Z) (0.19%)", "domain": "Particle, BT-20"},
    "(n/φ)/(σ-φ)": {"value": "3/10=0.300", "application": "sin²θ₁₂ neutrino (0.99%)", "domain": "Neutrino, BT-21"},
    "τ/(σ-sopfr)": {"value": "4/7=0.5714", "application": "sin²θ₂₃ neutrino (0.10%)", "domain": "Neutrino, BT-21"},
    "μ/σ": {"value": "1/12=0.0833", "application": "sin²(2θ₁₃) neutrino (0.91%)", "domain": "Neutrino, BT-21"},
    "1-μ/P₂": {"value": "27/28=0.96429", "application": "n_s spectral index (0.064%)", "domain": "Cosmology, BT-22"},
    "σ/σ(P₂)²": {"value": "12/3136≈0.00383", "application": "r = ", "domain": "V_ub"},
    "μ/J₂": {"value": "1/24=0.04167", "application": "", "domain": "V_cb"},
    "(n/φ+μ/σ)·10⁻ˢᵒᵖᶠʳ": {"value": "37/12×10⁻⁵", "application": "Jarlskog J (0.11%)", "domain": "Particle, BT-23"},
    "φ²/n": {"value": "2/3=0.66667", "application": "Koide formula (0.0009%!)", "domain": "Particle, BT-24"},
    "(σ+n/φ)/(σ-sopfr)": {"value": "15/7=2.1429", "application": "m_t/m_W (0.20%)", "domain": "Particle, BT-25"},
    "τ/(n/φ)": {"value": "4/3=1.333 eV", "application": "SQ optimal solar bandgap (0.50%)", "domain": "Energy, BT-30"},
    "J₂+φ": {"value": "26 mV", "application": "Thermal voltage V_T(300K) (0.57%)", "domain": "Chip+Thermal, BT-30"},
    "τ²/(n/φ)³": {"value": "16/27", "application": "Betz limit (wind turbine, EXACT)", "domain": "Energy, BT-30"},
    "σ²-φ": {"value": "142", "application": "H₂ HHV (MJ/kg, EXACT)", "domain": "Hydrogen, BT-38"},
    "(σ-φ)^τ": {"value": "10⁴", "application": "RoPE base θ (LLaMA)", "domain": "AI, BT-34"},
    "1-1/(σ-φ)": {"value": "0.9", "application": "Adam β₁ (ALL LLMs universal)", "domain": "AI, BT-54"},
    "10^{-(σ-τ)}": {"value": "1e-8", "application": "Adam ε (GPT-3/Qwen universal)", "domain": "AI, BT-54"},
    "σ·φ^τ": {"value": "192", "application": "B100/B200/MI300X HBM capacity (GB)", "domain": "Chip, BT-55"},
    "σ·J₂": {"value": "288", "application": "B300/Rubin HBM capacity (GB)", "domain": "Chip, BT-55"},
    "σ²-n/φ": {"value": "141", "application": "H200 HBM capacity (GB, EXACT)", "domain": "Chip, BT-55"},
    "σ·τ·(σ-φ)": {"value": "480", "application": "3-phase datacenter feed (V)", "domain": "Power, BT-60"},
    "σ/(σ-φ)": {"value": "1.2", "application": "Hyperscaler PUE target / DDR Vdd", "domain": "Power/Chip, BT-60"},
    "(σ-μ)/(σ-φ)": {"value": "1.10", "application": "Google fleet PUE (2021)", "domain": "Power, BT-60"},
    "(σ-φ)²·τ": {"value": "400", "application": "A100 TDP (W)", "domain": "Chip, BT-60"},
    "(σ-φ)³": {"value": "1000", "application": "B200 TDP (W)", "domain": "Chip, BT-60"},
    "(σ-φ)^(n/φ)": {"value": "10³ = 1000", "application": "DDPM timesteps T", "domain": "AI (Diffusion)"},
    "(σ-φ)^{-τ}": {"value": "10^{-4}", "application": "DDPM β_start", "domain": "AI (Diffusion)"},
    "φ/(σ-φ)^φ": {"value": "2/100 = 0.02", "application": "DDPM β_end", "domain": "AI (Diffusion)"},
    "(σ+n/φ)/φ": {"value": "15/2 = 7.5", "application": "CFG guidance scale", "domain": "AI (Diffusion)"},
    "sopfr·2^n": {"value": "320", "application": "Stable Diffusion base channels", "domain": "AI (Diffusion)"},
    "(n/φ)/(σ-φ)^φ": {"value": "0.03", "application": "LLM warmup ratio", "domain": "AI (Training)"},
    "σ²+τ": {"value": "148", "application": "B200 enabled SMs (dual die)", "domain": "Chip"},
    "2^(σ-τ)": {"value": "256", "application": "MI350X total CUs, TPU v6e MXU array", "domain": "Chip"},
    "J₂": {"value": "24 cores", "application": "NPU neural cores", "domain": "SoC"},
    "σ·J₂ [SoC]": {"value": "288 GB", "application": "Unified HBM4 memory", "domain": "SoC"},
    "σ·J₂ [System Level Cache (SLC)]": {"value": "288 MB", "application": "System Level Cache (SLC)", "domain": "SoC"},
    "J₂²": {"value": "576", "application": "Total Tensor Cores (σ²·τ)", "domain": "SoC"},
    "2^(σ-τ) [SoC]": {"value": "256 KB", "application": "L1/Shared memory per SM", "domain": "SoC"},
    "σ·sopfr·τ": {"value": "240 W", "application": "Total SoC TDP", "domain": "SoC"},
    "J₂·(σ-φ)": {"value": "240 W", "application": "Same TDP (dual derivation)", "domain": "SoC"},
    "σ/(σ-φ) [SoC, Power]": {"value": "1.2 V", "application": "Core voltage = PUE", "domain": "SoC, Power"},
    "2^sopfr": {"value": "32 Gbps", "application": "PAM4 per WDM wavelength", "domain": "Optical"},
    "σ·(σ-τ)·2^n": {"value": "6,144", "application": "Total PIM MACs per stack", "domain": "PIM"},
    "~25x": {"value": "BW amplification", "application": "Internal vs external bandwidth", "domain": "PIM"},
    "σ·J₂ [3D]": {"value": "288/mm²", "application": "TSV density", "domain": "3D"},
    "σ·(σ-τ)": {"value": "96/mm²", "application": "Power TSVs (1/3 of 288)", "domain": "3D"},
    "σ⁴": {"value": "20,736", "application": "Total signal TSVs on die", "domain": "3D"},
    "σ·J₂ [Total 3D stack TDP]": {"value": "288 W", "application": "Total 3D stack TDP", "domain": "3D"},
    "σ·(σ-τ) [3D]": {"value": "96 W", "application": "PIM layer power (1/3)", "domain": "3D"},
    "J₂ [3D]": {"value": "24 GB", "application": "Capacity per DRAM layer", "domain": "3D"},
    "σ×σ": {"value": "12×12=144", "application": "MZI mesh size (matrix multiply)", "domain": "Photonic"},
    "~0.01 pJ": {"value": "—", "application": "Energy per photonic MAC", "domain": "Photonic"},
    "σ²·σ·J₂": {"value": "41,472 GB ≈ 41.5 TB", "application": "Total memory", "domain": "Wafer"},
    "σ²·240W": {"value": "34,560 W ≈ 35 kW", "application": "Total power", "domain": "Wafer"},
    "σ²·τ/2": {"value": "288", "application": "Total mesh links", "domain": "Wafer"},
    "2^σ": {"value": "4,096 GB/s", "application": "Per-link bandwidth", "domain": "Wafer"},
    "~10⁻¹⁹ J": {"value": "—", "application": "RSFQ energy per operation", "domain": "SC"},
    "~10⁻²¹ J": {"value": "—", "application": "AQFP energy per operation", "domain": "SC"},
    "σ-φ": {"value": "10 Gbps", "application": "Per-fiber data rate", "domain": "SC, Optical"},
    "σ(n)·φ(n)=n·τ(n)": {"value": "24=24", "application": "Master identity (unique at n=6)", "domain": "ALL"},
    "BT-1": {"value": "φ(6)=2 Universal Pairing", "application": "Cooper pair, D(A=2), Φ₀=h/2e, SQUID, MgB₂ 2-gap, Type I/II, He-3 pair (7 domains)", "domain": "🟩⭐⭐"},
    "BT-2": {"value": "τ(6)=4 Bohm-BCS Bridge", "application": "Bohm 1/2⁴ loss + BCS T⁴ protection + 4 MHD modes + 4 d-wave nodes", "domain": "🟩⭐⭐"},
    "BT-3": {"value": "σ(6)=12 Energy Scale Convergence", "application": "BCS ΔC numerator EXACT + C-12 triple-alpha + ~12T magnets + gauge generators", "domain": "🟩⭐⭐"},
    "BT-4": {"value": "MHD Divisor Theorem", "application": "All 4 dangerous q-surfaces {1,3/2,2,3} from div(6)={1,2,3}, p≈0.01", "domain": "🟩⭐"},
    "BT-5": {"value": "q=1 = Σ(1/d) = Perfect Number Definition", "application": "Egyptian fraction = Kruskal-Shafranov stability", "domain": "🟩⭐⭐⭐"},
    "BT-20": {"value": "Gauge Coupling Trinity", "application": "1/α=σ(σ-μ)+sopfr+1/P₂ (2ppm), α_s=5/42 (0.97%), sin²θ_W=3/13 (0.19%)", "domain": "🟩⭐⭐⭐"},
    "BT-21": {"value": "Neutrino Mixing Trident", "application": "sin²θ₁₂=3/10, sin²θ₂₃=4/7, sin²(2θ₁₃)=1/12 — all <1%", "domain": "🟩⭐⭐"},
    "BT-22": {"value": "Inflation from Perfect Numbers", "application": "n_s=27/28 (0.064%), N=σ(P₂)=56, r=12/3136 testable", "domain": "🟩⭐⭐⭐"},
    "BT-23": {"value": "CKM Quark Mixing Hierarchy", "application": "", "domain": "V_ub"},
    "BT-24": {"value": "Koide Pole Residue", "application": "Q=φ²/n=2/3 (0.0009%!) — most precise mass formula", "domain": "🟩⭐⭐⭐"},
    "BT-25": {"value": "Genetic Code Arithmetic", "application": "64=φⁿ=τⁿ/φ, 20=J₂-τ=m_s/m_d, τ=φ²(n=6 only)", "domain": "🟩⭐⭐"},
    "BT-26": {"value": "Chinchilla Scaling Constants", "application": "α=1/3, β=ln(4/3), tokens/params=J₂-τ=20 (0.0% EXACT)", "domain": "🟩⭐⭐"},
    "BT-27": {"value": "Carbon-6 Energy Chain", "application": "LiC₆(n)+C₆H₁₂O₆(n,σ,n)+C₆H₆(n)→24e=J₂", "domain": "🟩⭐⭐"},
    "BT-28": {"value": "Computing Architecture Ladder", "application": "AD102=σ·n·φ=144, H100=σ(σ-μ)=132SMs=1/α term, HBM τ→σ-τ→σ, 30+EXACT", "domain": "🟩⭐⭐⭐"},
    "BT-29": {"value": "IEEE 519 Power Quality", "application": "THD=sopfr=5%, individual=n/φ=3%, TDD=σ-τ=8%", "domain": "🟩⭐⭐"},
    "BT-30": {"value": "SQ Solar Bridge", "application": "Bandgap=τ/(n/φ)=4/3eV (0.50%), V_T=(J₂+φ)mV (0.57%)", "domain": "🟩⭐⭐"},
    "BT-31": {"value": "MoE Top-k Vocabulary", "application": "{μ,φ,n,σ-τ}={1,2,6,8} — all published MoE top-k values", "domain": "🟩⭐⭐"},
    "BT-32": {"value": "Nuclear Fission Scaffold", "application": "6 delayed neutron groups=n, B-10=sopfr·φ, enrichment=[n/φ,sopfr]%", "domain": "🟩⭐"},
    "BT-33": {"value": "Transformer σ=12 Atom", "application": "d=σ·2^k, heads=σ, SwiGLU=8/3=(σ-τ)/(n/φ), LoRA r=σ-τ", "domain": "🟩⭐"},
    "BT-34": {"value": "RoPE Base & Decimal Bridge", "application": "θ=(σ-φ)^{τ,sopfr,n}={10⁴,10⁵,10⁶}, WD=1/(σ-φ), β₂=1-1/(J₂-τ)", "domain": "🟩⭐⭐"},
    "BT-35": {"value": "Battery Voltage Table", "application": "7/8 chemistries: 1.2=n/sopfr, 1.5=n/τ, 2.0=φ, 3.0=n/φ, 4.0=τ", "domain": "🟩⭐"},
    "BT-36": {"value": "Grand Energy-Info-HW-Physics Chain", "application": "Solar→Semiconductor→Landauer→H100→1/α, 5 links all <1%", "domain": "🟩⭐⭐⭐"},
    "BT-37": {"value": "Semiconductor Pitch Ladder", "application": "N5 pitch=P₂=28nm, N3 gate=σ·τ=48nm, 8/8 EXACT", "domain": "🟩⭐⭐"},
    "BT-38": {"value": "Hydrogen Energy Quadruplet", "application": "LHV=σ(σ-φ)=120, HHV=σ²-φ=142, Gibbs=113,118 — 4/4 EXACT, diffs also n=6", "domain": "🟩⭐⭐"},
    "BT-39": {"value": "KV-Head Universality", "application": "n_kv_heads∈{σ-τ,2^τ} 5/5 models, Mistral L2 5/6 n=6, d_ff=P₂·1024", "domain": "🟩⭐⭐"},
    "BT-40": {"value": "Computing Power Ecosystem", "application": "ATX 12V=σ, ACPI triple-τ (C/D/G=4), S=n=6, car 6×2V=n×φ=σ", "domain": "🟩⭐⭐"},
    "BT-41": {"value": "QEC at J₂", "application": "Surface d=5: 24 syndrome=J₂=Golay, d=3: 17=σ+sopfr, QV=2^(J₂-τ)", "domain": "🟩⭐⭐"},
    "BT-54": {"value": "AdamW Training Quintuplet", "application": "β₁=1-1/(σ-φ), β₂=1-1/(J₂-τ), ε=10^{-(σ-τ)}, λ=1/(σ-φ), clip=R(6)=1", "domain": "🟩⭐⭐⭐"},
    "BT-55": {"value": "GPU HBM Capacity Ladder", "application": "14/18 EXACT: 40=τ(σ-φ), 80=φ^τ·sopfr, 192=σ·φ^τ, 288=σ·J₂", "domain": "🟩⭐⭐"},
    "BT-56": {"value": "Complete n=6 LLM Architecture", "application": "d=2^σ, L=2^sopfr, d_h=2^(σ-sopfr)=128, 4 teams converge", "domain": "🟩⭐⭐⭐"},
    "BT-58": {"value": "σ-τ=8 Universal AI Constant", "application": "LoRA, MoE, KV, FlashAttn, batch, quant, 16/16 EXACT", "domain": "🟩⭐⭐⭐"},
    "BT-59": {"value": "8-Layer AI Stack", "application": "silicon→precision→memory→compute→arch→train→opt→inference", "domain": "🟩⭐⭐⭐"},
    "BT-60": {"value": "DC Power Chain", "application": "120→480→48→12→1.2→1V, PUE=σ/(σ-φ)=1.2, 6/6 EXACT", "domain": "🟩⭐⭐"},
    "BT-61": {"value": "Diffusion n=6 Universality", "application": "DDPM T=10³, β=10^{-4}~2/100, DDIM=50, CFG=7.5, 9/9 EXACT", "domain": "🟩⭐⭐⭐"},
    "BT-62": {"value": "Grid Frequency Pair", "application": "60Hz=σ·sopfr, 50Hz=sopfr·(σ-φ), ratio=PUE=σ/(σ-φ)=1.2", "domain": "🟩⭐⭐"},
    "BT-63": {"value": "Solar Panel Cell Ladder", "application": "60=σ·sopfr, 72=σ·n, 120=σ(σ-φ), 144=σ², cross=H₂+GPU", "domain": "🟩⭐⭐"},
    "BT-64": {"value": "Universal Regularization 0.1", "application": "WD=DPO β=GPTQ=cosine=Mamba=KL=1/(σ-φ), 7 algorithms", "domain": "🟩⭐⭐⭐"},
    "BT-65": {"value": "Mamba SSM Complete n=6", "application": "d_state=2^τ, expand=φ, d_conv=τ, dt_max=1/(σ-φ), 6/6 EXACT", "domain": "🟩⭐⭐"},
    "Li-6 dual decomposition (A+Z)": {"value": "P1→τ+P1/φ", "application": "A and Z both P1 arithmetic", "domain": "TECS-L FENGR-001"},
    "D-T-Li6 fuel cycle mass numbers": {"value": "{1,2,3,4,6}", "application": "div(6)∪{τ}", "domain": "Complete fuel cycle"},
    "Triple-alpha 3×He-4→C-12": {"value": "3τ=σ=12", "application": "3×τ(6)=σ(6)", "domain": "Stellar nucleosynthesis"},
    "q=1 = 1/2+1/3+1/6": {"value": "Σ(1/d)=1", "application": "Perfect number definition", "domain": "Kruskal-Shafranov"},
    "Tritium half-life": {"value": "12.32 yr", "application": "σ(6)=12", "domain": "2.6%"},
    "D-T optimal temp": {"value": "~14 keV", "application": "σ+φ=14", "domain": "±1 keV"},
    "He-4 binding energy": {"value": "28.296 MeV", "application": "P2=28", "domain": "1.1%"},
    "SPARC B_T": {"value": "12.2 T", "application": "σ(6)=12", "domain": "1.7%"},
    "D-T cross-section peak": {"value": "~64 keV", "application": "2^n=64", "domain": "±10%"},
    "H-mode improvement factor": {"value": "~2×", "application": "φ(6)=2", "domain": "±30%"},
    "MHD dangerous modes from div(6)": {"value": "4 modes, m,n∈{1,2,3}", "application": "τ(6) modes, div(6) numbers", "domain": "p≈0.01"},
    "Bohm diffusion 1/16": {"value": "2⁴=16", "application": "2^τ(6)", "domain": "exact in formula"},
    "D-He3 Q-value": {"value": "18.3 MeV", "application": "3n=18", "domain": "1.7%"},
    "Nb₃Sn Tc": {"value": "18.3 K", "application": "3n=18", "domain": "1.7%"},
    "BCS isotope exponent": {"value": "α=1/2", "application": "1/φ(6)", "domain": "ω_D ∝ M^(-1/2)"},
    "Flux quantum Φ₀ = h/(2e)": {"value": "2e", "application": "φ(6)·e", "domain": "Cooper pair charge"},
    "YBCO Y₁Ba₂Cu₃ metal ratio": {"value": "1:2:3", "application": "proper div(6), sum=6=n", "domain": "Perovskite structure"},
    "WHH coefficient": {"value": "ln2=0.693", "application": "ln(φ(6))", "domain": "BCS linearization"},
    "MgB₂ Mg atomic number": {"value": "Z=12", "application": "σ(6)", "domain": "Element property"},
    "MgB₂ B atomic number": {"value": "Z=5", "application": "sopfr(6)", "domain": "Element property"},
    "Kissing number chain": {"value": "K₂=6→K₃=12→K₂₄=Leech", "application": "n→σ→J₂ (dim)", "domain": "Sphere packing math"},
    "Type I/II classification": {"value": "2 types", "application": "φ(6)", "domain": "exact count"},
    "Nb₃Sn Hc2(4.2K)": {"value": "24-27 T", "application": "J₂(6)=24", "domain": "0-12%"},
    "Nb₃Sn Hc2(0K)": {"value": "~28-30 T", "application": "P2=28", "domain": "0-7%"},
    "He-4 boiling point": {"value": "4.222 K", "application": "τ(6)=4", "domain": "5.6%"},
    "SC qubit base types": {"value": "3 (charge/flux/phase)", "application": "n/φ", "domain": "exact count"},
    "SC phase space (T,H,J)": {"value": "3 axes", "application": "n/φ", "domain": "exact count"},
    "He-3 Cooper pair total A": {"value": "2×3=6", "application": "φ×(n/φ)=n", "domain": "exact"},
    "BCS 2Δ/kTc coefficient 2π": {"value": "2π=φ·π", "application": "φ(6)·π", "domain": "exact in formula"},
    "ITER all coil types = multiples of 6": {"value": "PF=6,CS=6,TF=18,CC=18", "application": "n,n,3n,3n", "domain": "P(chance)≈0.5%"},
    "Nb₃Sn A15: 6 Nb → Tc=18 → Hc2=24": {"value": "6→18→24", "application": "n→3n→J₂", "domain": "Solid-state causal chain"},
    "ITER TF peak field": {"value": "11.8 T", "application": "σ(6)=12", "domain": "1.7%"},
    "Quench protection stages": {"value": "4 (detect/spread/dump/break)", "application": "τ(6)", "domain": "exact count"},
    "AC loss components": {"value": "4 (hysteresis/coupling/eddy/mag)", "application": "τ(6)", "domain": "exact count"},
    "EM-thermal-structural coupling": {"value": "3 physics fields", "application": "n/φ", "domain": "exact count"},
    "Cooling methods": {"value": "3 (pool/forced/conduction)", "application": "n/φ", "domain": "exact count"},
    "LTS operating temp": {"value": "~4.2 K", "application": "τ(6)=4", "domain": "5%"},
    "HTS/LTS field boundary": {"value": "~12 T", "application": "σ(6)", "domain": "practical boundary"},
    "He-4 + He-3 coolants": {"value": "2 isotopes", "application": "φ(6)", "domain": "exact count"},
    "X-point snowflake (2nd order null)": {"value": "6 branches", "application": "n", "domain": "Topological necessity: 2(k+1), k=2"},
    "X-point standard (1st order null)": {"value": "4 branches", "application": "τ(6)", "domain": "Topological necessity: 2(k+1), k=1"},
    "q=1 = Egyptian fraction": {"value": "1/2+1/3+1/6=1", "application": "Σ(1/d)=1", "domain": "Perfect number definition ≡ K-S limit"},
    "ITER port allocation quad": {"value": "diag=6,NBI=3,ECH=4,ICH=2", "application": "n,n/φ,τ,φ", "domain": "Independent engineering choices"},
    "Blanket functions": {"value": "4 (shield/heat/breed/face)", "application": "τ(6)", "domain": "exact count"},
    "Disruption response stages": {"value": "4 (avoid/predict/mitigate/survive)", "application": "τ(6)", "domain": "exact count"},
    "ITER port allocation detail": {"value": "diag=6,NBI=3,ECH=4,ICH=2", "application": "n,n/φ,τ,φ", "domain": "system-level match"},
    "Fuel injection methods": {"value": "3 (gas/pellet/NBI)", "application": "n/φ", "domain": "exact count"},
    "Plasma startup sequence": {"value": "6 steps", "application": "n", "domain": "exact count"},
    "Startup 6-phase causal chain": {"value": "6 steps (physics necessity)", "application": "n", "domain": "causal sequence"},
    "MHD island width from div(6)": {"value": "{1,2,3} only", "application": "proper div(6)", "domain": "Low-order dominance"},
    "Divertor detachment stages": {"value": "3 (attached/partial/full)", "application": "n/φ", "domain": "standard classification"},
    "Bohm diffusion coefficient": {"value": "1/16 = 2⁻⁴", "application": "2⁻τ⁽⁶⁾", "domain": "semi-empirical constant"},
    "ST/conventional boundary": {"value": "A = 2", "application": "φ(6)", "domain": "CS geometry threshold"},
    "q₉₅=3 operating point": {"value": "σ/τ=12/4=3", "application": "σ(6)/τ(6)", "domain": "ITER baseline (not universal)"},
    "P_fus ∝ B⁴ deep derivation": {"value": "exponent 4 = τ(6)", "application": "τ(6)", "domain": "n²<σv> → β²B⁴V chain"},
    "NTM stabilization strategies": {"value": "3 (ECCD/rotation/profile)", "application": "n/φ", "domain": "standard classification"},
    "Steady-state barriers": {"value": "4 (divertor/impurity/coil/current)", "application": "τ(6)", "domain": "KSTAR team standard"},
    "Snowflake 6-leg heat spreading": {"value": "2-3× reduction per n legs", "application": "n", "domain": "H-TK-73 EXACT applied"},
    "Bootstrap fraction threshold": {"value": "50% = 1/2", "application": "1/φ(6)", "domain": "fusion community standard"},
    "ECCD gyrotrons targeting rational surfaces": {"value": "4 surfaces (q=1,3/2,2,off-axis)", "application": "τ(6)", "domain": "H-TK-63 applied"},
    "Heating methods": {"value": "3 (NBI/ECH/ICH)", "application": "n/φ", "domain": "standard classification"},
    "6π⁵": {"value": "1836.118", "application": "m_p/m_e = 1836.153", "domain": "0.002%"},
    "3/(σ+μ) = 3/13": {"value": "0.2308", "application": "sin²θ_W = 0.2312", "domain": "0.19%"},
    "4π/(σ+sopfr-φ) = 4π/15": {"value": "0.8378", "application": "r_p = 0.8414 fm", "domain": "0.43%"},
    "σ·√(Δm²₂₁)": {"value": "0.104 eV", "application": "Σm_ν < 0.12 eV", "domain": "within bound"},
    "Ext Binary Golay": {"value": "[24, 12, 8]", "application": "[J₂, σ, σ-τ]", "domain": ""},
    "Ext Ternary Golay": {"value": "[12, 6, 6]", "application": "[σ, n, n]", "domain": ""},
    "Hamming(7,4,3)": {"value": "[7, 4, 3]", "application": "[σ-sopfr, τ, n/φ]", "domain": ""},
    "Golay code [24,12,8]": {"value": "[24,12,8]", "application": "[J₂, σ, σ-τ]", "domain": "Coding theory"},
    "AES-256 key size": {"value": "256 bit", "application": "2^(σ-τ) = 2^8", "domain": "NIST standard"},
    "SHA-256 output": {"value": "256 bit", "application": "2^(σ-τ)", "domain": "NIST standard"},
    "RSA-2048 key": {"value": "2048 bit", "application": "2^(σ-μ) = 2^11", "domain": "NIST standard"},
    "RSA public exponent": {"value": "65537 = F₄", "application": "F_{τ(6)} (last Fermat prime)", "domain": "PKCS#1/RFC 3110"},
    "BLS12-381 embedding degree": {"value": "k = 12", "application": "σ(6)", "domain": "Pairing crypto standard"},
    "BLS12 tower extension": {"value": "[2,3,2]", "application": "[φ, n/φ, φ] palindrome", "domain": "Field arithmetic"},
    "ML-DSA-65 parameters": {"value": "(k=6, l=5)", "application": "(n, sopfr) 2-param match", "domain": "NIST PQC Level 3"},
    "DRBG reseed interval": {"value": "2⁴⁸", "application": "2^(σ·τ)", "domain": "NIST SP 800-90A"},
    "Ethereum slot time": {"value": "12 s", "application": "σ(6)", "domain": "Beacon chain spec"},
    "IPv6 address": {"value": "128 bit", "application": "2^(σ-sopfr) = 2^7", "domain": "RFC 8200"},
    "5G NR numerology": {"value": "5 configs", "application": "sopfr(6)", "domain": "3GPP TS 38.211"},
    "DNS header": {"value": "12 bytes", "application": "σ", "domain": "RFC 1035"},
    "RTP fixed header": {"value": "12 bytes", "application": "σ", "domain": "RFC 3550"},
    "ARP packet (IPv4/Eth)": {"value": "28 bytes", "application": "J₂+τ (= 2nd perfect number)", "domain": "RFC 826"},
    "MAC address": {"value": "6 bytes", "application": "n", "domain": "IEEE 802.3"},
    "Ethernet min frame": {"value": "64 bytes", "application": "2^n = 2^6", "domain": "IEEE 802.3"},
    "IPv4 min header": {"value": "20 bytes", "application": "J₂-τ", "domain": "RFC 791"},
    "TCP min header": {"value": "20 bytes", "application": "J₂-τ", "domain": "RFC 793"},
    "IPv6 fixed header": {"value": "40 bytes", "application": "φ·(J₂-τ)", "domain": "RFC 8200"},
    "UDP header": {"value": "8 bytes", "application": "σ-τ", "domain": "RFC 768"},
    "TCP+DNS = core theorem": {"value": "11+13=24", "application": "σ·φ = n·τ = J₂", "domain": "BT-13 ⭐⭐⭐"},
    "Golay code [24,12,8] [Perfect code]": {"value": "all params", "application": "[J₂, σ, σ-τ]", "domain": "Perfect code"},
    "Hamming code [7,4,3]": {"value": "all params", "application": "[σ-sopfr, τ, n/φ]", "domain": "Perfect code"},
    "6-pulse rectifier": {"value": "6 pulses", "application": "n = 3-phase × 2", "domain": "Power electronics"},
    "12-pulse HVDC": {"value": "12 pulses", "application": "σ(6)", "domain": "HVDC standard"},
    "Pulse chain 6→12→24": {"value": "n→σ→J₂", "application": "n=6 divisor chain", "domain": "Power electronics"},
    "IEEE 519 THD limit": {"value": "5%", "application": "sopfr(6)", "domain": "IEEE 519-2014"},
    "Power market structure": {"value": "4 markets", "application": "τ(6)", "domain": "PJM/CAISO"},
    "Apple M-series power split": {"value": "50:33:17", "application": "1/2:1/3:1/6", "domain": "Die analysis"},
    "Hamming ECC [7,4,3]": {"value": "[7,4,3]", "application": "[σ-sopfr, τ, n/φ]", "domain": "ECC memory"},
    "PCIe doubling per gen": {"value": "×2", "application": "φ(6)", "domain": "PCIe spec"},
    "AD102 GPCs": {"value": "**12**", "application": "**σ**", "domain": "NVIDIA Ada Lovelace"},
    "AD102 TPCs/GPC": {"value": "**6**", "application": "**n**", "domain": "NVIDIA Ada Lovelace"},
    "AD102 SMs/TPC": {"value": "**2**", "application": "**φ**", "domain": "NVIDIA (all gens since 2012)"},
    "AD102 full die": {"value": "**144 SMs**", "application": "**σ² = σ·n·φ**", "domain": "NVIDIA RTX 4090"},
    "H100 enabled SMs": {"value": "**132**", "application": "**σ(σ-μ) = 12·11**", "domain": "NVIDIA Hopper (= 1/α leading term)"},
    "H100 GPCs": {"value": "**8**", "application": "**σ-τ**", "domain": "NVIDIA Hopper"},
    "H100 TC/SM": {"value": "**4**", "application": "**τ**", "domain": "NVIDIA Ampere+"},
    "H100 CUDA/SM": {"value": "**128**", "application": "**2^(σ-sopfr)**", "domain": "NVIDIA Hopper"},
    "H100/A100 HBM stacks": {"value": "**5**", "application": "**sopfr**", "domain": "NVIDIA"},
    "H100/A100 memory": {"value": "**80 GB**", "application": "**sopfr·2^τ**", "domain": "NVIDIA"},
    "RTX 4090 VRAM": {"value": "**24 GB**", "application": "**J₂**", "domain": "NVIDIA Ada"},
    "A100 NVLink links": {"value": "**12**", "application": "**σ**", "domain": "NVIDIA Ampere"},
    "B200 SMs/die": {"value": "**192**", "application": "**σ·2^τ**", "domain": "NVIDIA Blackwell"},
    "CUDA warp": {"value": "**32**", "application": "**2^sopfr**", "domain": "NVIDIA (all gens)"},
    "HBM1 stack": {"value": "**4-hi**", "application": "**τ**", "domain": "SK Hynix"},
    "HBM2e stack": {"value": "**8-hi**", "application": "**σ-τ**", "domain": "SK Hynix / Samsung"},
    "HBM3 stack": {"value": "**12-hi**", "application": "**σ**", "domain": "SK Hynix"},
    "HBM channels/stack": {"value": "**8**", "application": "**σ-τ**", "domain": "HBM2/2e spec"},
    "HBM bus width": {"value": "**1024 bit**", "application": "**(σ-τ)·2^(σ-sopfr)**", "domain": "HBM spec"},
    "x86 GPR count": {"value": "**16**", "application": "**2^τ**", "domain": "Intel/AMD"},
    "AVX/RISC-V registers": {"value": "**32**", "application": "**2^sopfr**", "domain": "ISA spec"},
    "Classic RISC pipeline": {"value": "**5 stages**", "application": "**sopfr**", "domain": "Patterson/Hennessy"},
    "Apple M3 Pro cores": {"value": "**12**", "application": "**σ**", "domain": "Apple"},
    "GB200 dual die": {"value": "**2 die**", "application": "**φ**", "domain": "NVIDIA Blackwell"},
    "GB200 total SMs": {"value": "**384**", "application": "**σ·2^sopfr**", "domain": "NVIDIA GB200"},
    "B200 GPCs": {"value": "**12**", "application": "**σ**", "domain": "NVIDIA Blackwell"},
    "B200 TPCs/GPC": {"value": "**8**", "application": "**σ-τ**", "domain": "NVIDIA Blackwell"},
    "B200 HBM stacks": {"value": "**6**", "application": "**n**", "domain": "NVIDIA Blackwell"},
    "B200 VRAM": {"value": "**192 GB**", "application": "**σ·2^τ**", "domain": "NVIDIA Blackwell"},
    "HBM4 stack": {"value": "**16-hi**", "application": "**2^τ**", "domain": "SK Hynix 2025"},
    "HBM4 channels": {"value": "**16**", "application": "**2^τ**", "domain": "HBM4 spec"},
    "HBM4 bus width": {"value": "**2048 bit**", "application": "**2^(σ-μ)**", "domain": "HBM4 spec"},
    "PCIe 7.0": {"value": "**128 GT/s**", "application": "**2^(σ-sopfr)**", "domain": "PCI-SIG roadmap"},
    "Gaudi 3 MME": {"value": "**8**", "application": "**σ-τ**", "domain": "Intel Habana"},
    "Agile values + principles": {"value": "4 + 12", "application": "τ + σ", "domain": "Agile Manifesto"},
    "Golay quantum code": {"value": "[[24,12,8]]", "application": "[J₂, σ, σ-τ]", "domain": "Coding theory"},
    "Ternary Golay": {"value": "[12,6,6]", "application": "[σ, n, n]", "domain": "GF(3) code"},
    "Clifford generators": {"value": "3 {H,S,CNOT}", "application": "n/φ", "domain": "Group theory"},
    "Color code [[6,4,2]]": {"value": "[6,4,2]", "application": "[n, τ, φ]", "domain": "QEC"},
    "BB84: 4 states, 2 bases": {"value": "4, 2", "application": "τ, φ", "domain": "QKD protocol"},
    "Kissing K₂=6, K₃=12": {"value": "6, 12", "application": "n, σ", "domain": "Sphere packing"},
    "Landauer limit": {"value": "kT·ln(2)", "application": "kT·ln(φ(6))", "domain": "Thermodynamics"},
    "Stefan-Boltzmann T⁴": {"value": "exponent 4", "application": "τ(6)", "domain": "Radiation law"},
    "JEDEC thermal model": {"value": "4 RC stages", "application": "τ(6)", "domain": "JESD51"},
    "Phi6 activation": {"value": "x²-x+1", "application": "Φ₆(x)", "domain": "6th cyclotomic"},
    "Boltzmann exploration": {"value": "1/e ≈ 0.368", "application": "e^(-1)", "domain": "Information theory"},
    "Shockley-Queisser limit": {"value": "~33.7% ≈ 1/3", "application": "1/(n/φ)", "domain": "Solar physics"},
    "DNA bases": {"value": "4 (A,T,G,C)", "application": "τ(6)", "domain": "Molecular biology"},
    "Glucose C₆H₁₂O₆": {"value": "(6,12,6)", "application": "(n, σ, n)", "domain": "Chemistry"},
    "Benzene C₆H₆": {"value": "6 carbons, 6π e⁻", "application": "n", "domain": "Chemistry"},
    "SM fermion types": {"value": "3×4 = 12", "application": "(n/φ)×τ = σ", "domain": "Core theorem realization"},
    "SM with antimatter": {"value": "24 species", "application": "J₂ = σ·φ = n·τ", "domain": "Core theorem value"},
    "SU(5)→SM decomp": {"value": "24=12+12", "application": "J₂ = σ+σ = σ·φ", "domain": "Gauge boson split"},
    "1/α fine structure": {"value": "137.0357 vs 137.0360", "application": "σ(σ-μ)+sopfr+1/P₂", "domain": "**2.1 ppm**"},
    "6π⁵ ≈ m_p/m_e": {"value": "1836.118 vs 1836.153", "application": "6π⁵", "domain": "19 ppm"},
    "α_s strong coupling": {"value": "0.1190 vs 0.1179", "application": "sopfr/((σ-sopfr)·n)=5/42", "domain": "0.97%"},
    "m_n/m_p - 1": {"value": "1/720 vs 0.001378", "application": "1/n! = 1/720", "domain": "0.79%"},
    "σn+μ ≈ H₀": {"value": "73 vs 73.04", "application": "σn+μ", "domain": "0.05%"},
    "ζ(2) = π²/6": {"value": "π²/n", "application": "Euler (1735)", "domain": "Number theory"},
    "B₂ = 1/6": {"value": "1/n", "application": "Bernoulli number", "domain": "Number theory"},
    "6 = 1+2+3 = 1×2×3": {"value": "unique", "application": "n", "domain": "Number theory"},
    "Egyptian fraction uniqueness": {"value": "1/2+1/3+1/6=1", "application": "Σ(1/d)=1", "domain": "n=6 only"},
    "S₆ outer automorphism": {"value": "unique S_n", "application": "n=6", "domain": "Group theory"},
    "Golay [24,12,8]": {"value": "[J₂,σ,σ-τ]", "application": "Three params", "domain": "Coding theory"},
    "Hexacode [6,3,4] over GF(4)": {"value": "[n,n/φ,τ]", "application": "Three params", "domain": "Coding theory"},
    "χ_orb(Y(1)) = -1/6": {"value": "-1/n", "application": "Orbifold Euler char", "domain": "Modular curve"},
    "ζ(-1) = -1/12": {"value": "-1/σ", "application": "Ramanujan sum", "domain": "Number theory"},
    "Crystallographic max symmetry": {"value": "6-fold", "application": "n", "domain": "2D restriction"},
    "K₁..₄ sequence": {"value": "(2,6,12,24)", "application": "(φ,n,σ,J₂)", "domain": "4 proved theorems"},
    "2D tiling symmetries": {"value": "{3,4,6}", "application": "{n/φ,τ,n}", "domain": "Crystallography"},
    "PSL₂(Z) generator order": {"value": "6 (ST)", "application": "n", "domain": "Modular group"},
    "Page size": {"value": "4096 = 2^12", "application": "2^σ", "domain": "Memory management"},
    "PWM resolution (robotics)": {"value": "12-bit", "application": "σ(6)", "domain": "Servo control"},
    "Python indentation": {"value": "4 spaces", "application": "τ(6)", "domain": "PEP 8"},
    "Ethereum MaxEB": {"value": "2048", "application": "2^(σ-μ)", "domain": "EIP-7251"},
    "LiC₆ stoichiometry C:Li": {"value": "6:1", "application": "n", "domain": "Li-ion anode"},
    "Bohm diffusion 1/16 [Plasma physics]": {"value": "2^(-4)", "application": "2^(-τ)", "domain": "Plasma physics"},
    "DeepSeek-V3 routed experts": {"value": "256", "application": "2^(σ-τ)", "domain": "DS-V3"},
    "DeepSeek-V3 KV dim (compressed)": {"value": "512", "application": "2^(σ-n/φ)", "domain": "DS-V3 (MLA)"},
    "Llama 4 FFN width": {"value": "8192", "application": "2^(σ+μ)", "domain": "Llama 4"},
    "Llama 4 iRoPE NoPE period": {"value": "4 layers", "application": "τ", "domain": "Llama 4 iRoPE"},
    "Llama 4 context": {"value": "256K", "application": "2^(σ+n) = 2^18", "domain": "Llama 4"},
    "Llama 3.1 context": {"value": "128K", "application": "2^(σ+sopfr) = 2^17", "domain": "Llama 3.1"},
    "Qwen2.5 14B/32B hidden": {"value": "5120", "application": "sopfr·2^(σ-φ)", "domain": "Qwen 2.5"},
    "Qwen2.5 72B (= Llama 70B)": {"value": "d=8192, L=80, h=64", "application": "2^(σ+μ), φ^τ·sopfr, 2^n", "domain": "2 independent teams"},
    "AdamW triplet (5-team verified)": {"value": "β₁=0.9, β₂=0.95, wd=0.1", "application": "1-1/(σ-φ), 1-1/(J₂-τ), 1/(σ-φ)", "domain": "GPT-3/Llama/DS/Qwen/DBRX"},
    "Total Experts": {"value": "n=6 Expression", "application": "Model(s)", "domain": ""},
    "Top-k": {"value": "n=6 Expression", "application": "Model(s)", "domain": ""},
    "Context": {"value": "n=6 Exponent", "application": "Model(s)", "domain": ""},
    "2K": {"value": "2^(σ-μ) = 2^11", "application": "GPT-3", "domain": ""},
    "4K": {"value": "2^σ = 2^12", "application": "Llama 1/2, Mistral", "domain": ""},
    "8K": {"value": "2^(σ+μ) = 2^13", "application": "Llama 3", "domain": ""},
    "32K": {"value": "2^(σ+n/φ+φ) = 2^17?", "application": "Mistral Large", "domain": ""},
    "128K": {"value": "2^(σ+sopfr) = 2^17", "application": "Llama 3.1", "domain": ""},
    "256K": {"value": "2^(σ+n) = 2^18", "application": "Llama 4", "domain": ""},
    "DDPM timesteps T": {"value": "1000", "application": "(σ-φ)^(n/φ) = 10³", "domain": "Ho et al. 2020"},
    "DDPM β_start": {"value": "0.0001", "application": "(σ-φ)^{-τ} = 10^{-4}", "domain": "Ho et al. 2020"},
    "DDPM β_end": {"value": "0.02", "application": "φ/(σ-φ)^φ = 2/100", "domain": "Ho et al. 2020"},
    "DDIM/DDPM acceleration": {"value": "20×", "application": "J₂-τ = Chinchilla ratio", "domain": "= BT-26"},
    "SD spatial compression": {"value": "8×", "application": "σ-τ", "domain": "Rombach et al. 2022"},
    "SD base channels": {"value": "320", "application": "sopfr·2^n = 5·64", "domain": "Rombach et al. 2022"},
    "U-Net channel multipliers": {"value": "[1,2,4,8]", "application": "[μ,φ,τ,σ-τ]", "domain": "Ho et al. 2020"},
    "CFG guidance scale": {"value": "7.5", "application": "(σ+n/φ)/φ = 15/2", "domain": "Ho & Salimans 2022"},
    "supported kernels": {"value": "{2,3,4}", "application": "{φ, n/φ, τ}", "domain": "Gu & Dao 2023"},
    "Mamba-2 d_state ladder": {"value": "{16,64,128,256}", "application": "2^{τ,n,σ-sopfr,σ-τ}", "domain": "Dao & Gu 2024"},
    "Algorithm": {"value": "Parameter", "application": "Value", "domain": "Year"},
    "AdamW": {"value": "weight_decay", "application": "0.1", "domain": "2019"},
    "InstructGPT": {"value": "KL coefficient", "application": "0.1", "domain": "2022"},
    "DPO": {"value": "β", "application": "0.1", "domain": "2023"},
    "GPTQ": {"value": "damp_percent", "application": "0.1", "domain": "2023"},
    "Cosine LR": {"value": "min_ratio", "application": "0.1", "domain": "2020+"},
    "PPO": {"value": "clip ε / 2", "application": "0.1", "domain": "2017"},
    "60Hz/50Hz ratio": {"value": "1.2", "application": "σ/(σ-φ) = PUE", "domain": "Cross to BT-60"},
    "Grid 400kV": {"value": "400", "application": "τ·(σ-φ)² = A100 TDP", "domain": "Cross to BT-60"},
    "BESS 4-hour standard": {"value": "4 hr", "application": "τ", "domain": "CPUC/ERCOT"},
    "EV 400V platform": {"value": "400V", "application": "τ·(σ-φ)²", "domain": "Tesla/Chevy"},
    "EV 800V platform": {"value": "800V", "application": "φ·τ·(σ-φ)²", "domain": "Hyundai/Porsche"},
    "DCFC 50kW tier": {"value": "50 kW", "application": "sopfr·(σ-φ)", "domain": "CHAdeMO/CCS"},
    "DCFC input voltage": {"value": "480V", "application": "σ·τ·(σ-φ)", "domain": "3-phase industrial"},
    "ITER plasma current": {"value": "15 MA", "application": "σ+n/φ", "domain": "ITER design"},
    "ITER major radius": {"value": "6.2 m", "application": "n+φ/10", "domain": "ITER design"},
    "SPARC B-field": {"value": "12.2 T", "application": "σ+φ/10", "domain": "CFS SPARC"},
    "SPARC Q target": {"value": "~11", "application": "σ-μ", "domain": "CFS SPARC design"},
    "τ·(σ-φ)²": {"value": "400", "application": "Grid 400kV, EV 400V", "domain": "A100 400W TDP"},
    "Flux quantum Φ₀ = h/(2e) [Superconductor]": {"value": "2 (denominator)", "application": "φ(6)", "domain": "Superconductor"},
    "Spatial inertia matrix": {"value": "6×6, 4 blocks", "application": "n×n, τ blocks", "domain": "Robotics"},
    "Hexacopter fault tolerance": {"value": "6 rotors, 5 min", "application": "n, sopfr", "domain": "Robotics"},
    "Linux CFS base quantum": {"value": "6 ms", "application": "n", "domain": "OS scheduler"},
    "YBCO metal ratio Y:Ba:Cu": {"value": "1:2:3 = proper div(6)", "application": "sum=n", "domain": "HTS crystal"},
    "ITER port allocation": {"value": "(6,3,4,2)", "application": "(n, n/φ, τ, φ) 4-param", "domain": "ITER engineering"},
    "E₇ rank / E₈ rank": {"value": "7 / 8", "application": "σ-sopfr / σ-τ", "domain": "Exceptional Lie"},
    "π₃ˢ stable homotopy": {"value": "Z/24", "application": "Z/J₂(6)", "domain": "Algebraic topology"},
    "Eisenstein E₄, E₆ weights": {"value": "4, 6", "application": "τ, n", "domain": "Modular forms"},
    "(2,3,6) triangle": {"value": "1/2+1/3+1/6=1", "application": "Euclidean boundary", "domain": "Hyperbolic geometry"},
    "Todd class coefficient": {"value": "1/12", "application": "1/σ = B₂/2", "domain": "Algebraic geometry"},
    "PSL₂(Z) generator orders": {"value": "{2,3}, ST order 6", "application": "primes of n", "domain": "Modular group"},
    "Perovskite ABX₃ B-site CN": {"value": "6 (octahedral)", "application": "n", "domain": "Solar cell / battery"},
    "Leech lattice QEC bound": {"value": "24 dim", "application": "J₂(6)", "domain": "Quantum error correction"},
    "sin²θ_W": {"value": "0.2312", "application": "3/(σ+μ) = 3/13", "domain": "0.19%"},
    "m_τ/m_μ": {"value": "16.82", "application": "σ+sopfr = 17", "domain": "1.1%"},
    "μ_p (proton moment)": {"value": "2.793", "application": "14/sopfr = 14/5", "domain": "0.26%"},
    "μ_n (neutron moment)": {"value": "-1.913", "application": "-23/σ = -23/12", "domain": "0.19%"},
    "m_p/m_π": {"value": "6.72", "application": "47/(σ-sopfr) = 47/7", "domain": "0.12%"},
    "m_n/m_p - 1 [0.77%]": {"value": "0.001378", "application": "1/6! = 1/720", "domain": "0.77%"},
    "Bitcoin 21M supply": {"value": "21×10⁶", "application": "(σ+τ+sopfr)×10⁶", "domain": "Whitepaper"},
    "EVM word size": {"value": "256 bit", "application": "2^(σ-τ)", "domain": "Yellow Paper"},
    "ORU challenge period": {"value": "7 days", "application": "σ-sopfr", "domain": "Optimistic rollup"},
    "BT-5 [⭐⭐⭐]": {"value": "q=1 = Σ(1/d) = Perfect Number", "application": "tokamak+math", "domain": "⭐⭐⭐"},
    "BT-6": {"value": "Golay-Leech Unification [J₂,σ,σ-τ]", "application": "quantum, crypto, network, chip, math", "domain": "⭐⭐⭐"},
    "BT-7": {"value": "Egyptian Fraction Power Theorem 1/2+1/3+1/6=1", "application": "power, chip, thermal, AI, tokamak", "domain": "⭐⭐"},
    "BT-8": {"value": "Pulse Rectifier Chain n→σ→J₂", "application": "power, tokamak, chip, math", "domain": "⭐⭐"},
    "BT-9": {"value": "Bott Periodicity Bridge σ-τ=8", "application": "quantum, crypto, topology, SM", "domain": "⭐"},
    "BT-10": {"value": "Landauer-WHH Bridge ln(φ)=ln(2)", "application": "thermal, info, superconductor", "domain": "⭐⭐"},
    "BT-11": {"value": "Software-Physics Isomorphism", "application": "software, physics, math", "domain": "⭐"},
    "BT-12": {"value": "Hamming-OSI-ECC Triple Bridge [7,4,3]", "application": "network, chip, quantum", "domain": "⭐⭐"},
    "BT-13": {"value": "σ±μ Internet Infrastructure Duality", "application": "network, math, coding, crypto", "domain": "⭐⭐⭐"},
    "BT-14": {"value": "Carbon-Silicon Tetrahedral Bridge", "application": "nuclear, bio, chip, network, crypto, math", "domain": "⭐⭐"},
    "BT-15": {"value": "Kissing Number Quadruple K₁..₄=(φ,n,σ,J₂)", "application": "math, superconductor, nuclear, coding", "domain": "⭐⭐⭐"},
    "BT-16": {"value": "Riemann Zeta Trident ζ(2)=π²/n, ζ(-1)=-1/σ, BCS=σ/(7ζ(3))", "application": "math, number theory, superconductor, AI", "domain": "⭐⭐⭐"},
    "BT-17": {"value": "SM Fermion-Boson σ-Balance: (n/φ)×τ = σ = generators", "application": "particle physics, math, number theory", "domain": "⭐⭐"},
    "BT-18": {"value": "Vacuum Energy Chain: E₀=-(σφ)⁻¹ → η²⁴ → Δ(wt σ) → Monster", "application": "QFT, modular forms, coding, lattice, group theory", "domain": "CONJECTURE"},
    "BT-19": {"value": "GUT Hierarchy: ranks (τ,sopfr,n,σ-τ), dim(SU(5))=J₂, 11/11", "application": "particle physics, Lie algebra, string theory", "domain": "⭐⭐⭐"},
    "BT-26 [⭐⭐]": {"value": "Chinchilla scaling: tokens/params=J₂-τ=20", "application": "AI, info theory, number theory, chip", "domain": "⭐⭐"},
    "BT-28 [⭐⭐⭐]": {"value": "Computing architecture ladder: 30+ EXACT", "application": "chip (GPU/CPU/HBM), AI, coding, crypto", "domain": "⭐⭐⭐"},
    "BT-33 [⭐]": {"value": "Transformer σ=12 atom: BERT/GPT dims", "application": "AI, chip, coding, physics", "domain": "⭐"},
    "BT-36 [⭐⭐⭐]": {"value": "Grand Energy-Info-Hardware-Physics chain", "application": "solar, semiconductor, info, chip, physics", "domain": "⭐⭐⭐"},
    "BT-38 [⭐⭐]": {"value": "Hydrogen quadruplet: 4/4 EXACT + 4 diffs", "application": "hydrogen, thermo, fuel cell, energy", "domain": "⭐⭐"},
    "BT-42": {"value": "Inference scaling: top-p=1-1/(J₂-τ)=0.95", "application": "AI inference, info theory, chip", "domain": "⭐⭐"},
    "BT-43": {"value": "Battery cathode CN=6 universality", "application": "battery, chemistry, energy, materials", "domain": "⭐⭐⭐"},
    "BT-44": {"value": "Context window ladder: σ-φ→σ-μ→σ→σ+μ", "application": "AI/LLM, info theory, chip", "domain": "⭐⭐"},
    "BT-48": {"value": "Display-Audio: σ=12 semitones, J₂=24", "application": "music, display, audio, color, MIDI", "domain": "⭐⭐⭐"},
    "BT-49": {"value": "Pure Math: K₁..₄=(φ,n,σ,J₂), B₂=1/n, S₆", "application": "math, coding theory, lattice, group theory", "domain": "⭐⭐⭐"},
    "BT-51": {"value": "Genetic code: τ→n/φ→2^n→J₂-τ chain", "application": "biology, info theory, chemistry", "domain": "⭐⭐⭐"},
    "BT-53": {"value": "Crypto: BTC 21M=J₂-n/φ, ETH 12s=σ", "application": "blockchain, crypto, info theory", "domain": "⭐⭐"},
    "BT-54 [⭐⭐⭐]": {"value": "AdamW quintuplet: β₁=1-1/(σ-φ), β₂=1-1/(J₂-τ), ε=10^{-(σ-τ)}, λ=1/(σ-φ), clip=R(6)", "application": "AI/LLM, optimization, training", "domain": "⭐⭐⭐"},
    "BT-55 [⭐⭐]": {"value": "GPU HBM ladder: 40=τ(σ-φ), 80=φ^τ·sopfr, 192=σ·φ^τ, 288=σ·J₂", "application": "chip, memory, HPC, AI infra", "domain": "⭐⭐"},
    "BT-56 [⭐⭐⭐]": {"value": "Complete n=6 LLM: d=2^σ, L=2^sopfr, h=2^sopfr, d_h=2^(σ-sopfr)=128", "application": "AI arch, scaling, chip, info theory", "domain": "⭐⭐⭐"},
    "BT-57": {"value": "Battery cell ladder: 6→12→24 cells = n→σ→J₂, Tesla 96S=σ(σ-τ)", "application": "electrochem, auto, telecom, energy", "domain": "⭐⭐"},
    "BT-58 [⭐⭐⭐]": {"value": "σ-τ=8 universal AI constant: LoRA, MoE, KV, FlashAttn, batch (16/16)", "application": "AI train, inference, memory, precision", "domain": "⭐⭐⭐"},
    "BT-59 [⭐⭐⭐]": {"value": "8-layer AI stack: silicon→precision→memory→compute→arch→train→opt→inference", "application": "ALL AI domains, 8 independent layers", "domain": "⭐⭐⭐"},
    "BT-60 [⭐⭐]": {"value": "Datacenter power chain: 120→480→48→12→1.2→1V, PUE=σ/(σ-φ)=1.2", "application": "power grid, DC infra, chip, AI", "domain": "⭐⭐"},
    "BT-66": {"value": "Vision AI complete n=6", "application": "ViT+CLIP+Whisper+SD3+Flux.1, 24/24 EXACT", "domain": "🟩⭐⭐⭐"},
    "BT-67": {"value": "MoE activation fraction law", "application": "1/2^{μ,φ,n/φ,τ,sopfr}, 6 models EXACT", "domain": "🟩⭐⭐⭐"},
    "BT-68": {"value": "HVDC voltage ladder", "application": "±500/800/1100kV = {sopfr,σ-τ,σ-μ}·(σ-φ)², 10/10", "domain": "🟩⭐⭐"},
    "BT-69": {"value": "Chiplet architecture convergence", "application": "B300=160, R100 σ=12, 5 vendors, 17/20", "domain": "🟩⭐⭐⭐"},
    "BT-70": {"value": "0.1 convergence 8th algorithm", "application": "SimCLR temp, count=σ-τ=8 meta-n=6", "domain": "🟩⭐⭐"},
    "BT-71": {"value": "NeRF/3DGS complete n=6", "application": "L=σ-φ=10, layers=σ-τ=8, SH=n/φ=3, 7/7", "domain": "🟩⭐⭐"},
    "BT-72": {"value": "Neural audio codec n=6", "application": "EnCodec 8 codebooks, 1024 entries, 24kHz, 7/7", "domain": "🟩⭐⭐"},
    "BT-73": {"value": "Tokenizer vocabulary law", "application": "32K/50257/100K/128K = 2^a·(σ-φ)^b, 6/6", "domain": "🟩⭐⭐"},
    "BT-74": {"value": "95/5 cross-domain resonance", "application": "top-p=PF=β₂=0.95, THD=β_plasma=5%, 5 domains", "domain": "🟩⭐⭐⭐"},
    "BT-75": {"value": "HBM interface exponent ladder", "application": "{10,11,12}={σ-φ,σ-μ,σ}, HBM5 predicted", "domain": "🟩⭐⭐"},
    "BT-76": {"value": "σ·τ=48 triple attractor", "application": "gate pitch nm, HBM4E GB, 48kHz, 48V, 3DGS SH", "domain": "🟩⭐⭐"},
    "BT-77": {"value": "Quantization/BitNet complete", "application": "40/41 EXACT (97.6%), 3 models × 2 teams", "domain": "🟩⭐⭐⭐"},
    "BT-78": {"value": "KV cache compression n=6", "application": "MLA+GQA+CLA+FlashAttn+PagedAttn, 45/46", "domain": "🟩⭐⭐⭐"},
    "BT-79": {"value": "Speculative decoding n=6", "application": "draft=sopfr=5, Medusa 64=2^n nodes, 30/33", "domain": "🟩⭐⭐⭐"},
    "BT-80": {"value": "Solid-state electrolyte CN=6", "application": "NASICON/Garnet/LLZO=CN=6, sulfide=τ=4, 6/6", "domain": "🟩⭐⭐⭐"},
    "BT-81": {"value": "Anode capacity ladder σ-φ=10x", "application": "Si/Graphite=9.62x≈σ-φ, Li Metal=10.38x≈σ-φ", "domain": "🟩⭐⭐"},
    "BT-82": {"value": "Battery pack n=6 map", "application": "6→12→24 cells, 96S/192S EV, BMS div(6)", "domain": "🟩⭐⭐"},
    "BT-83": {"value": "Li-S polysulfide ladder", "application": "S₈→S₄→S₂→S₁ = (σ-τ)→τ→φ→μ, 5/6", "domain": "🟩⭐⭐"},
    "BT-84": {"value": "96/192 triple convergence", "application": "Tesla 96S=Gaudi2 96GB=GPT-3 96L, 5/5", "domain": "🟩⭐⭐⭐"},
    "BT-85": {"value": "Carbon n=6 universality", "application": "Z=6, allotropes=τ, C₆₀ penta=σ, 16/18 (88.9%)", "domain": "🟩⭐⭐⭐"},
    "BT-86": {"value": "Octahedral CN=6 universality", "application": "20+ materials all CN=6, 23/24 (95.8%)", "domain": "🟩⭐⭐⭐"},
    "BT-87": {"value": "Precision fabrication ladder", "application": "STM/ALD/MBE=1/(σ-φ), EUV=σ-φ, 11/14", "domain": "🟩⭐⭐"},
    "BT-88": {"value": "Hexagonal emergence universality", "application": "12 independent systems all 6-fold, 18/18 (100%)", "domain": "🟩⭐⭐"},
    "BT-89": {"value": "Photonic-Energy n=6 Bridge", "application": "TDP 10x=σ-φ, PUE=1.2, E-O=90%, 11/15 EXACT (93.3%)", "domain": "🟩⭐⭐"},
    "BT-90": {"value": "SM = φ×K₆ 접촉수 정리", "application": "σ²=144=φ×K₆, SM hierarchy=K₁×K₂×K₃, 6/6 EXACT", "domain": "🟩⭐⭐⭐"},
    "BT-91": {"value": "Z2 위상 ECC J₂ 절약", "application": "savings=σ·J₂/σ=J₂=24GB, mathematical identity", "domain": "🟩⭐⭐"},
    "BT-92": {"value": "Bott 활성 채널 = sopfr", "application": "active=5=sopfr, trivial=3=n/φ, 5/8≈1-1/e", "domain": "🟩⭐⭐⭐"},
    "BT-93": {"value": "Carbon Z=6 칩 소재 보편성", "application": "Diamond/Graphene/SiC=Z=6, 8/10 Cross-DSE 1위", "domain": "🟩⭐⭐⭐"},
    "Full domain (derived set)": {"value": "0.74", "application": "❌ NO", "domain": ""},
    "Fusion base-only (7 constants)": {"value": "3.71", "application": "✅ YES", "domain": ""},
    "Fusion Monte Carlo (10K)": {"value": "29%ile", "application": "❌ NO", "domain": ""},
    "SM gauge partition": {"value": "~8%", "application": "⚠️ WEAK", "domain": ""},
    "TECS-L cross-domain (70 hyp)": {"value": "81.4% hit vs 20% baseline", "application": "✅ YES (4× above chance)", "domain": ""},
    "σ·2^n": {"value": "768", "application": "ViT-B d_model", "domain": "Dosovitskiy 2021"},
    "2^(σ-φ)": {"value": "1024", "application": "ViT-L d_model", "domain": "Dosovitskiy 2021"},
    "sopfr·2^(σ-τ)": {"value": "1280", "application": "ViT-H d_model", "domain": "Dosovitskiy 2021"},
    "σ·2^(σ-sopfr)": {"value": "1536", "application": "DINOv2-g d_model", "domain": "Oquab 2023"},
    "(σ-sopfr)·2^sopfr": {"value": "224", "application": "CV input resolution", "domain": "ImageNet"},
    "(n/φ)/τ": {"value": "0.75", "application": "MAE mask ratio", "domain": "He 2022"},
    "2^(σ-τ+μ)": {"value": "512", "application": "CLIP embed dim", "domain": "Radford 2021"},
    "(σ-sopfr)/φ": {"value": "3.5", "application": "Flux.1 guidance scale", "domain": "Black Forest Labs"},
    "1/2^τ": {"value": "1/16 = 0.0625", "application": "MoE activation fraction", "domain": "Llama 4, Qwen3 MoE"},
    "1/2^sopfr": {"value": "1/32 = 0.03125", "application": "MoE activation fraction", "domain": "DeepSeek-V3"},
    "1/2^(σ-μ)": {"value": "1/2048", "application": "MoE activation fraction", "domain": "GShard, Switch"},
    "sopfr·(σ-φ)²": {"value": "500", "application": "HVDC ±500kV", "domain": "ABB/Siemens"},
    "(σ-τ)·(σ-φ)²": {"value": "800", "application": "HVDC ±800kV", "domain": "State Grid China"},
    "(σ-μ)·(σ-φ)²": {"value": "1100", "application": "UHVDC ±1100kV", "domain": "Changji-Guquan"},
    "(σ+n/φ)·(σ-φ)": {"value": "150", "application": "Fusion temp (million K)", "domain": "ITER/SPARC"},
    "(σ+n/φ)/(σ-φ)": {"value": "1.5", "application": "Perovskite bandgap (eV)", "domain": "Solar"},
    "J₂·10³": {"value": "24000", "application": "Sample rate (Hz)", "domain": "Défossez 2022"},
    "{n/τ,n/φ,n,σ,J₂}": {"value": "{1.5,3,6,12,24}", "application": "Bandwidth ladder (kbps)", "domain": "EnCodec"},
    "sopfr·(σ-φ)^τ+2^(σ-τ)+μ": {"value": "50257", "application": "GPT-2 BPE vocab", "domain": "OpenAI"},
    "(σ-φ)^sopfr": {"value": "100000", "application": "Tiktoken cl100k", "domain": "OpenAI"},
    "φ·(σ-φ)^sopfr": {"value": "200000", "application": "Tiktoken o200k", "domain": "OpenAI"},
    "2^sopfr·(σ-φ)^(n/φ)": {"value": "32000", "application": "Llama 1/2 vocab", "domain": "Meta"},
    "2^(σ-sopfr)·(σ-φ)^(n/φ)": {"value": "128000", "application": "Llama 3 vocab", "domain": "Meta"},
    "2^(σ-φ) [SK Hynix]": {"value": "1024 bits", "application": "HBM3 interface width", "domain": "SK Hynix"},
    "2^(σ-μ)": {"value": "2048 bits", "application": "HBM4 interface width", "domain": "SK Hynix 2025"},
    "2^σ [Roadmap]": {"value": "4096 bits", "application": "HBM5 interface width (predicted)", "domain": "Roadmap"},
    "2^sopfr [PCI-SIG / UCIe]": {"value": "32 GT/s", "application": "PCIe 5.0 / UCIe 2.0", "domain": "PCI-SIG / UCIe"},
    "2^(σ-sopfr)": {"value": "128 GT/s", "application": "PCIe 7.0 / CXL 4.0", "domain": "PCI-SIG"},
    "2^(σ-τ) [Roadmap]": {"value": "256 GT/s", "application": "PCIe 8.0 (predicted)", "domain": "Roadmap"},
    "Graphene bond angle": {"value": "120°", "application": "σ·(σ-φ)", "domain": "Geometry"},
    "CNT armchair index": {"value": "(6,6)", "application": "(n,n)", "domain": "Nanotube"},
    "STM lateral resolution": {"value": "0.1 nm", "application": "1/(σ-φ)", "domain": "Scanning probe"},
    "ALD per cycle thickness": {"value": "0.1 nm", "application": "1/(σ-φ)", "domain": "Thin film deposition"},
    "MBE growth rate": {"value": "0.1 nm/s", "application": "1/(σ-φ)", "domain": "Epitaxy"},
    "AFM vertical resolution": {"value": "0.01 nm", "application": "1/(σ·(σ-φ))", "domain": "Scanning probe"},
    "SPM single atom precision": {"value": "0.01 nm", "application": "(σ-φ)^{-2}", "domain": "Atom manipulation"},
    "EUV lithography resolution": {"value": "10 nm", "application": "σ-φ", "domain": "ASML"},
    "FIB milling resolution": {"value": "10 nm", "application": "σ-φ", "domain": "Ion beam"},
    "E-beam lithography": {"value": "1 nm", "application": "μ", "domain": "Electron beam"},
    "TSMC N3 gate pitch": {"value": "48 nm", "application": "σ·τ", "domain": "Semiconductor"},
    "Optical diffraction limit": {"value": "~200 nm", "application": "φ·(σ-φ)^φ", "domain": "Abbe limit"},
    "Total scale ratio": {"value": "10⁶", "application": "(σ-φ)^n", "domain": "0.1nm→100mm"},
    "Graphene lattice symmetry": {"value": "6-fold", "application": "n", "domain": "2D material"},
    "Honeycomb (bees)": {"value": "6-fold", "application": "n", "domain": "Biology"},
    "Snowflakes": {"value": "6-fold", "application": "n", "domain": "Crystallography"},
    "Basalt columns": {"value": "6-fold", "application": "n", "domain": "Geology"},
    "Bénard convection cells": {"value": "6-fold", "application": "n", "domain": "Fluid dynamics"},
    "Bubble raft 2D": {"value": "6-fold", "application": "n", "domain": "Surface tension"},
    "Abrikosov vortex lattice": {"value": "6-fold", "application": "n (= K₂)", "domain": "Superconductor"},
    "Wigner crystal": {"value": "6-fold", "application": "n", "domain": "Solid-state physics"},
    "Colloidal crystal 2D": {"value": "6-fold", "application": "n", "domain": "Soft matter"},
    "Block copolymer domains": {"value": "6-fold", "application": "n", "domain": "Polymer science"},
    "Lipid membrane domains": {"value": "6-fold", "application": "n", "domain": "Biophysics"},
    "Saturn north pole": {"value": "6-fold", "application": "n", "domain": "Planetary science"},
    "Hex tiling angle": {"value": "120°", "application": "σ·(σ-φ)", "domain": "Geometry"},
    "Hexagonal edge-sharing": {"value": "6 edges", "application": "n", "domain": "Topology"},
    "Thomson N=12 icosahedron": {"value": "12 pentagons", "application": "σ", "domain": "Electrostatics"},
    "HCP coordination number": {"value": "6 neighbors", "application": "n", "domain": "Materials science"},
    "φ·σ(σ-τ)": {"value": "192", "application": "NIF laser beams", "domain": "LLNL"},
    "1/(n/φ)": {"value": "0.333", "application": "Steam Rankine cycle eff", "domain": "Power eng"},
    "n→σ→J₂": {"value": "6→12→24", "application": "Pulse rectifier ladder", "domain": "Power electronics"},
    "(σ-φ)^n": {"value": "10⁶", "application": "Total scale ratio (0.1nm→100mm)", "domain": "Assembly theory"},
    "(n,n)": {"value": "(6,6)", "application": "CNT armchair index", "domain": "Nanotube"},
    "1/(σ-φ)": {"value": "0.1 nm", "application": "STM/ALD/MBE precision", "domain": "Fabrication"},
    "1/(σ·(σ-φ))": {"value": "0.01 nm", "application": "AFM/SPM precision", "domain": "Metrology"},
    "μ": {"value": "1 nm", "application": "E-beam lithography", "domain": "Lithography"},
    "σ-φ [ASML]": {"value": "10 nm", "application": "EUV/FIB resolution", "domain": "ASML"},
    "σ²·J₂": {"value": "3456", "application": "Max cells per ESS container", "domain": "BT-82"},
    "1-1/(σ-φ) [Photonic]": {"value": "0.9 (90%)", "application": "Electro-optic conversion efficiency", "domain": "Photonic"},
    "(σ-φ)^(n/φ) [Photonic]": {"value": "10³", "application": "Photonic bandwidth/W advantage", "domain": "Photonic"},
    "J₂ [Math]": {"value": "24 = K₄", "application": "4D kissing number (D4 lattice)", "domain": "Math"},
    "σ·n": {"value": "72 = K₆", "application": "6D kissing number (E6 lattice)", "domain": "Math"},
    "σ·J₂/σ": {"value": "J₂ = 24 GB", "application": "Z2 topo ECC savings over SECDED", "domain": "Chip, Topology"},
    "sopfr/(σ-τ)": {"value": "5/8 = 0.625", "application": "Active channel fraction ≈ 1−1/e = 0.632 (0.71% diff)", "domain": "Topology, AI"},
    "--": {"value": "8/10", "application": "Cross-DSE material #1 = Carbon Z=6 based (80%)", "domain": "Cross-DSE"},
}
